# Generated by Django 2.1.7 on 2019-04-03 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customerFirstName', models.CharField(default='Prenom', max_length=50)),
                ('customerLastName', models.CharField(default='Nom', max_length=15)),
                ('customerEmail', models.CharField(default='Email', max_length=50)),
                ('doctor', models.CharField(default='Docteur', max_length=50)),
                ('customerNumber', models.CharField(default='Numero', max_length=50)),
                ('day', models.DateField(blank=True, null=True)),
                ('hour', models.DateTimeField(blank=True, null=True, verbose_name='Heure')),
            ],
        ),
        migrations.CreateModel(
            name='Appreciation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(default='Titre de la categorie', max_length=400)),
                ('type', models.CharField(choices=[('suggestion', 'suggestion'), ('comment', 'commentaire')], max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='Titre de la categorie', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('localisation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='Titre de lactualité', max_length=150)),
                ('image', models.ImageField(null=True, upload_to='news/%Y/%m/%d/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='Titre du service', max_length=150)),
                ('categorie', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='clinicApp.Categorie')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clinicApp.Service'),
        ),
    ]
